/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Mood = IDL.Variant({
  'sad' : IDL.Null,
  'anxious' : IDL.Null,
  'happy' : IDL.Null,
  'okay' : IDL.Null,
  'overwhelmed' : IDL.Null,
});
export const Time = IDL.Int;
export const Entry = IDL.Record({
  'id' : IDL.Nat,
  'nickname' : IDL.Opt(IDL.Text),
  'mood' : Mood,
  'text' : IDL.Text,
  'response' : IDL.Text,
  'timestamp' : Time,
});

export const idlService = IDL.Service({
  'addEntry' : IDL.Func([IDL.Opt(IDL.Text), Mood, IDL.Text], [IDL.Nat], []),
  'deleteEntry' : IDL.Func([IDL.Nat], [], []),
  'getEntriesByNickname' : IDL.Func([IDL.Text], [IDL.Vec(Entry)], ['query']),
  'getEntryCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getRecentEntries' : IDL.Func([], [IDL.Vec(Entry)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Mood = IDL.Variant({
    'sad' : IDL.Null,
    'anxious' : IDL.Null,
    'happy' : IDL.Null,
    'okay' : IDL.Null,
    'overwhelmed' : IDL.Null,
  });
  const Time = IDL.Int;
  const Entry = IDL.Record({
    'id' : IDL.Nat,
    'nickname' : IDL.Opt(IDL.Text),
    'mood' : Mood,
    'text' : IDL.Text,
    'response' : IDL.Text,
    'timestamp' : Time,
  });
  
  return IDL.Service({
    'addEntry' : IDL.Func([IDL.Opt(IDL.Text), Mood, IDL.Text], [IDL.Nat], []),
    'deleteEntry' : IDL.Func([IDL.Nat], [], []),
    'getEntriesByNickname' : IDL.Func([IDL.Text], [IDL.Vec(Entry)], ['query']),
    'getEntryCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getRecentEntries' : IDL.Func([], [IDL.Vec(Entry)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };