/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Category = IDL.Variant({
  'social' : IDL.Null,
  'justToday' : IDL.Null,
  'school' : IDL.Null,
  'personal' : IDL.Null,
  'health' : IDL.Null,
});
export const Time = IDL.Int;
export const Win = IDL.Record({
  'id' : IDL.Nat,
  'text' : IDL.Text,
  'response' : IDL.Text,
  'timestamp' : Time,
  'category' : IDL.Opt(Category),
});

export const idlService = IDL.Service({
  'addWin' : IDL.Func([IDL.Text, IDL.Opt(Category)], [IDL.Nat], []),
  'deleteWin' : IDL.Func([IDL.Nat], [], []),
  'getRecentWins' : IDL.Func([], [IDL.Vec(Win)], ['query']),
  'getWinCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getWinsByCategory' : IDL.Func([Category], [IDL.Vec(Win)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Category = IDL.Variant({
    'social' : IDL.Null,
    'justToday' : IDL.Null,
    'school' : IDL.Null,
    'personal' : IDL.Null,
    'health' : IDL.Null,
  });
  const Time = IDL.Int;
  const Win = IDL.Record({
    'id' : IDL.Nat,
    'text' : IDL.Text,
    'response' : IDL.Text,
    'timestamp' : Time,
    'category' : IDL.Opt(Category),
  });
  
  return IDL.Service({
    'addWin' : IDL.Func([IDL.Text, IDL.Opt(Category)], [IDL.Nat], []),
    'deleteWin' : IDL.Func([IDL.Nat], [], []),
    'getRecentWins' : IDL.Func([], [IDL.Vec(Win)], ['query']),
    'getWinCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getWinsByCategory' : IDL.Func([Category], [IDL.Vec(Win)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };