/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Entry {
    id: bigint;
    nickname?: string;
    mood: Mood;
    text: string;
    response: string;
    timestamp: Time;
}
export type Time = bigint;
export enum Mood {
    sad = "sad",
    anxious = "anxious",
    happy = "happy",
    okay = "okay",
    overwhelmed = "overwhelmed"
}
export interface backendInterface {
    addEntry(nickname: string | null, mood: Mood, text: string): Promise<bigint>;
    deleteEntry(id: bigint): Promise<void>;
    getEntriesByNickname(nickname: string): Promise<Array<Entry>>;
    getEntryCount(): Promise<bigint>;
    getRecentEntries(): Promise<Array<Entry>>;
}
import type { Entry as _Entry, Mood as _Mood, Time as _Time } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addEntry(arg0: string | null, arg1: Mood, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addEntry(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_Mood_n2(this._uploadFile, this._downloadFile, arg1), arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addEntry(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_Mood_n2(this._uploadFile, this._downloadFile, arg1), arg2);
            return result;
        }
    }
    async deleteEntry(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteEntry(arg0);
            return result;
        }
    }
    async getEntriesByNickname(arg0: string): Promise<Array<Entry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEntriesByNickname(arg0);
                return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEntriesByNickname(arg0);
            return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEntryCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getEntryCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEntryCount();
            return result;
        }
    }
    async getRecentEntries(): Promise<Array<Entry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecentEntries();
                return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecentEntries();
            return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_Entry_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Entry): Entry {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_Mood_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Mood): Mood {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    nickname: [] | [string];
    mood: _Mood;
    text: string;
    response: string;
    timestamp: _Time;
}): {
    id: bigint;
    nickname?: string;
    mood: Mood;
    text: string;
    response: string;
    timestamp: Time;
} {
    return {
        id: value.id,
        nickname: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.nickname)),
        mood: from_candid_Mood_n8(_uploadFile, _downloadFile, value.mood),
        text: value.text,
        response: value.response,
        timestamp: value.timestamp
    };
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    sad: null;
} | {
    anxious: null;
} | {
    happy: null;
} | {
    okay: null;
} | {
    overwhelmed: null;
}): Mood {
    return "sad" in value ? Mood.sad : "anxious" in value ? Mood.anxious : "happy" in value ? Mood.happy : "okay" in value ? Mood.okay : "overwhelmed" in value ? Mood.overwhelmed : value;
}
function from_candid_vec_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Entry>): Array<Entry> {
    return value.map((x)=>from_candid_Entry_n5(_uploadFile, _downloadFile, x));
}
function to_candid_Mood_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Mood): _Mood {
    return to_candid_variant_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Mood): {
    sad: null;
} | {
    anxious: null;
} | {
    happy: null;
} | {
    okay: null;
} | {
    overwhelmed: null;
} {
    return value == Mood.sad ? {
        sad: null
    } : value == Mood.anxious ? {
        anxious: null
    } : value == Mood.happy ? {
        happy: null
    } : value == Mood.okay ? {
        okay: null
    } : value == Mood.overwhelmed ? {
        overwhelmed: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
